paketo-buildpacks/occam

.github/workflows/create-release.yml
.github/workflows/test-pull-request.yml

Includes a workflows for:
- running tests against PRs
- cutting releases

Adds .github/workflows

---

matchers/contain_lines.go
matchers/contain_lines_test.go

matchers.ContainLines handles a fmt.Stringer missing [builder] prefix

---

buildpack_store.go

Signed-off-by: Forest Eckhardt <feckhardt@pivotal.io>

Make http requests with authorization token in header

---

pack.go
pack_test.go

Signed-off-by: Malini Valliath <mvalliath@pivotal.io>
Signed-off-by: Anthony Emengo <aemengo@vmware.com>
@aemengo

Add functionality for --trust-builder flag in pack build

---

.github/workflows/create-release.yml
.github/workflows/test-pull-request.yml

Signed-off-by: Ryan Moran <rmoran@vmware.com>

Use main instead of master branch

---

go.sum
pack.go
pack_test.go

- marks WithNoPull as deprecated
- `WithNoPull()` == `WithPullPolicy("never")`

Adds WithPullPolicy to occam.PackBuild

---

.github/workflows/lint.yml

Updates the linter action to the latest version
Fixes the lint workflow

Updates linter to latest version

---

docker.go
docker_test.go
pack.go
pack_test.go

- Also update Docker WithVolume to WithVolumes to match
This is needed in order to implement https://github.com/paketo-buildpacks/npm-install/issues/308.

Add pack.Build.WithVolumes()

---

matchers/be_available.go
matchers/contain_lines.go
matchers/serve.go

Resolves #79 
Resolves #80 
Resolves #81

Add API docs for occam matchers

---

docker.go
docker_test.go

Adds --network flag for run command

---

go.mod
go.sum

To test PR automation on the dependabot PR that will re-update its version
I want to test the automations added in #134, so I'm downgrading a dependency. I want to see what happens on the Dependabot PR that opens to re-bump it.

Downgrade freezer

---

matchers/serve.go
matchers/serve_test.go

This PR adds the ability to provide a `*http.Client` to the `ServeMatcher` via the helper method `ServeMatcher.WithClient()`.
This seems like the easiest way to allow consumers to bring their own client. Alternatives included making a new `ServeWithClient()` method, or adding an optional client to the existing `Serve()` method. Both of these options seemed more confusing and involved more code.
There are a variety of ways to test that we are using a provided HTTP client - the test we wrote was the simplest way to validate this.
This is based off #140 for convenience, so we should block this PR until that one is merged (or rebase off main if that PR is not merged in a timely manner).
The primary use-case for this is the integration tests for the `php-redis-session-handler` and …

Add custom HTTP client to serve matcher

---

.github/workflows/approve-bot-prs.yml

Rebase instead of squashing on auto-merge

---

README.md
go.mod
go.sum
init_test.go
testcontainers.go
testcontainers_test.go

Fixes #147 
This PR introduces `testcontainers` as helper to ease testing buildpacks.
```go
testContainer := occam.NewTestContainers()
container, err = testContainer.
WithExposedPorts("8080/tcp").
WithWaitingFor(wait.ForLog("Started App")).
Execute(imageName)
Expect(err).ShouldNot(HaveOccurred())
```

Add testcontainers as helper

---

docker.go
docker_test.go

Adds a command to the top-level `Docker` type that allows users to restart a running container.
Some buildpacks may need to test behavior when their built container restarts. For instance, we could use this new command to write a regression test for [this reported bug](https://github.com/paketo-buildpacks/npm-install/issues/382) in the `npm-install` buildpack.

Adds `docker container restart` command

---

docker.go
docker_test.go

Add helpers for `docker cp`, `docker exec`, and "docker exec with bash".

Add `docker cp` and `docker exec`

---

matchers/serve.go
matchers/serve_test.go

Sometimes, the `Serve` matcher returns an error because the port it's checking for a response is not in the container port map. This can happen because the container has failed to start properly. By adding container logs to the error output, occam can provide better visibility into failures like [this one](https://github.com/paketo-buildpacks/dotnet-publish/runs/7790043007?check_suite_focus=true).

Print container logs when Serve() does not find available port

---

matchers/serve.go
matchers/serve_test.go

Add WithHeader enhancement to the Serve matcher to check for a returned header

Add WithHeader enhancement to the Serve matcher to check for a returned header

---

source_test.go

Use matchers.BeAFileMatching

---

matchers/serve.go
matchers/serve_test.go

Fix Serve(WithHeader) so that it works with Eventually.
Since the `WithHeader` use case rewrote changed the response for the purpose of failure messages, this wouldn't work when called repeatedly with `Eventually`.

Fix Serve(WithHeader) so that it works with Eventually

---

docker.go
docker_test.go

Adds support for:
- `docker image tag`
- `--force` flag in docker image removal
An example use case is in the PHP language family integration tests, which currently use a separate docker client for these particular commands

Add image tag and remove with force

---

go.mod

remove toolchain from go.mod

---

README.md

Adding documentation about how to package a buildpack using libpak version 2.0.0 and above.

Updating readme for using new libpak

---

buildpack_store.go

Return the correct value from GetBuildpackRootAndVersion func.
This was missed during some refactoring while adding unit tests.

Return the correct value from GetBuildpackRootAndVersion func
