.github/workflows/create-release.yml
It would be nice to have a bit more control over releasing occam. This would allow us to bucket up some changes instead of releasing them on every commit.
=> Create draft releases of occam

matchers/be_available.go, matchers/be_available_test.go, matchers/fakes/executable.go, matchers/init_test.go
=> BeAvailable prints container logs when it fails

cache_volume_names.go, cache_volume_names_test.go, random_name.go, random_name_test.go
Using a custom registry domain ensures that we won't inadvertently trigger the run-image mirroring code that would be triggered when naming an image without a domain.
=> Use occam.example.com as registry prefix

matchers/contain_lines.go, matchers/contain_lines_test.go
In pack v0.11.0 and higher, the log output has changed. There is no longer a `[builder]` prefix on the build lines. We need to remove those prefixes so that `ContainLines` works with pack versions that either have these prefixes or not.
=> ContainLines handles logs from pack version 0.10.0 through 0.12.0

matchers/init_test.go, matchers/serve.go, matchers/serve_test.go
Implements a matcher that  checks whether a certain port on a container responds to an HTTP GET with a certain response. It can be used like:
`Eventually(container).Should(Serve("expected HTML content", "portOnContainer"))`.
@sophiewigmore and I noticed that we'd be repeating code to check the response from a certain app endpoint _very often_ in our tests for the samples repo. We figured it would be nice to have a matcher that cleanly checks this.
=> Serve matcher

cache_volume_names.go, cache_volume_names_test.go
The `pack` 0.17.0 release included what seemed to be an [innocuous change](https://github.com/buildpacks/pack/pull/1039) to the naming of the cache volumes. Unfortunately, this change resulted in our test harness failing to remove volumes after the tests were complete, and thus causing us to run out of disk when running certain test suites on constrained environments like GitHub Actions.
This change updates the list of volume names to remove such that includes the superset of those that would work for all versions of `pack`, including the latest 0.17.0 release.
=> Update CacheVolumeNames generation to support pack 0.17

docker.go, docker_test.go
Adds `WithVolume` to `DockerContainerRun` objects. 
This will allow us to set volume mounts when testing with occam docker containers in our tests. 
This came about as a part of https://github.com/paketo-buildpacks/nodejs/issues/308 since we will need to volume mount CA certificate bindings into the container.
=> add WithVolume support

.github/workflows/create-release.yml
The location of the action that increments the tag for a release was moved as part of https://github.com/paketo-buildpacks/github-config/pull/258. This fixes the release workflow to point to this new location.
=> Fixes action that increments tag in release workflow

buildpack_store.go, fakes/cache_manager.go, fakes/docker_image_inspect_client.go, fakes/executable.go, fakes/local_fetcher.go, fakes/remote_fetcher.go, matchers/fakes/executable.go
This will allow users to create a BuildpackStore that knows how to fetch and package non-packit buildpacks. Users define their own packager that implements the `freezer.Packager` interface, and BuildpackStore handles the rest. Presto!
=> add WithPackager to buildpackstore

buildpack_store.go, packagers/fakes/executable.go, packagers/init_test.go, packagers/jam.go, packagers/jam_test.go, packagers/libpak.go, packagers/libpak_test.go
Adds implementations of the `freezer.Packager` interface for `jam pack` and libpak's `create-package`. These can be used as arguments to `occam.BuildpackStore.WithPackager()`. Will enable users to easily select which packager is correct for the buildpacks they use in integration testing.
=> add jam and libpak implementations of freezer.Packager

container.go, matchers/be_available.go, matchers/serve.go
This PR makes adjustments so that you can configure a remote host. It will look at and parse `DOCKER_HOST`. If not set, then it defaults to `localhost` which preserves the current behavior. If set, it will parse the URL and return the hostname so long as it's not a `unix://` socket.
With the recent changes to Docker licensing, a user may not be running Docker on localhost. The occam code assumes that a test application will be accessible on `localhost` though. If you have a set up where Docker is running in a custom VM or even remotely. The occam matchers will always fail because nothing is available on localhost.
=> Support testing when Docker is not running locally

pack.go, pack_test.go
Resolves #126 
Easily extract SBOMs produced from builds. This unblocks paketo-buildpacks/go-mod-vendor#296 and many others.
=> Add pack build --sbom-output-dir

docker.go, docker_test.go
By adding this we will be able to pull some of our more complicated setup into our test suite. It will also facilitate a use case where you want to test with an already released buildpack. For example in our `samples` or in our `buildpackless-builder` test
=> Adds docker pull command

.github/workflows/approve-bot-prs.yml, .github/workflows/create-release.yml, .github/workflows/lint.yml, .github/workflows/test-pull-request.yml
An experiment that could help solve https://github.com/paketo-buildpacks/github-config/issues/451
Here, the workflow auto-approves PRs opened by bots that have only verified non-human commits. It also sets them to auto-merge once all required checks have passed. 
🚨 Before merging this PR, we'll need to turn on Enable Auto Merging in this repo's settings. 🚨
=> Enable auto-approve and auto-merge for bot PRs

buildpack_store.go, matchers/serve.go, source.go, source_test.go
This PR removes all references to the deprecated `ioutil` package and replaces them with their official replacements. See https://pkg.go.dev/io/ioutil for details on these replacements.
=> Remove references to deprecated ioutil package.

container.go, container_test.go, docker_test.go
Add a helper method to a running `Container` object to obtain the IP address of the container on a given network.
This makes it easy to get the IP address of a running container for a given network name. Without this, you essentially have to run `docker inspect` and manually traverse the returned json.
Given that the default network is so often called `bridge`, I could see an argument for adding a second helper method to obtain the IP address on this specific network - something like this:
```
func (c Container) IPAddressForBridgeNetwork() string)
```
Signed-off-by: Sophie Wigmore <swigmore@vmware.com>
=> Add method to get container IP address

docker.go, docker_test.go
As part of developing integration tests for the `jammy` tiny stack, we wanted to use the `occam` library to run an application image built with `pack build` with the new stack.
However, the `tiny` stack does not have a shell, meaning the docker command has to run directly, rather than with a shell. In practice this looks like:
```sh
docker run <image> -- <command> [args...]
```
Compared with the indirect invocation which looks like:
```sh
docker run <image> <command> [args...]
```
This requires two changes:
1. The ability to add the `--` flag to the docker command
2. The ability to specify the arguments that follow the command in docker run, rather than having the command include its arguments in a single string.
The ability to use `occam`'s docker run helper with an image that doesn't …
=> Support running direct processes via docker helper

docker.go, docker_test.go
By adding `WithReadOnly` and `WithMounts` we can test against containers that have their root filesystem marked as read-only.
Helps to resolve https://github.com/paketo-buildpacks/nginx/issues/385
=> Adds --read-only and --mount flags to container run command

builder.go, init_test.go, pack.go, pack_test.go
This addition will provide a first-class API for inspecting the details of a builder.
We have a few instances already across some test suites that could be improved if we used this common library code. For example, [this stack test helper function](https://github.com/paketo-buildpacks/jammy-tiny-stack/blob/6605249fa78f4a596be68dee8a9fa18054c9b46e/buildpack_integration_test.go#L176-L198).
=> Adds pack builder inspect command

image.go, image_test.go, init_test.go
This PR adds a helper method on `occam.Image` to easily facilitate looking up the metadata for a buildpack by its key. This enables consumers to avoid iterating through the buildpack array and/or hard-coding buildpack index.
There are multiple situations (e.g. [this](https://github.com/paketo-buildpacks/cpython/blob/4007b7fa690c607c3af8dde03d8a13b503256d05/integration/layer_reuse_test.go#L83-L84), and [this](https://github.com/paketo-buildpacks/go/blob/2b380ea3d70eec31da0ad48ef59495aa421409d0/integration/build_test.go#L129-L130)) where we hard-code the buildpack index. This is brittle, as it breaks if a buildpack is added to or removed from the build order.
=> Add BuildpackForKey helper method.

matchers/be_a_file_matching.go, matchers/be_a_file_matching_test.go, matchers/init_test.go
Add matchers.BeAFileMatching, which will allow you to match the contents of a file without having to write the file-reading code yourself!
=> Add matchers.BeAFileMatching

matchers/serve.go, matchers/serve_test.go
This PR adds a new `WithProtocol` method. This is useful for buildpacks which make `https` requests - like when httpd/nginx buildpacks leverage CA certificates.
It is hard to test this feature. I opted to validated that the request was made with `https` even though the server can't process that request. I did this by checking the returned error.
Configuring the server to respond to `https` requests is a lot of additional boilerplate, and I couldn't find another protocol that worked (e.g. `tcp` and `file` just returned an `unsupported protocol` error). I thought the `https` error is a more useful error to assert against.
=> Add WithProtocol to Serve matcher.

.github/workflows/create-draft-release.yml
Use the new way of producing outputs in a github action as the old way is deprecated and will be removed (31st May 2023).
This is needed, because `workflows/create-draft-release.yml` is listed in `.syncignore`
https://github.com/paketo-buildpacks/occam/blob/26019f3b25dbef03eaac4323b3040cf587277a7e/.github/.syncignore#L2
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See also: https://github.com/paketo-buildpacks/github-config/pull/604
Keep the pipelines alive.
=> Replace deprecated GHA ::set-output syntax

.github/workflows/test-pull-request.yml
See https://github.com/paketo-buildpacks/github-config/pull/715
Manual update needed because `test-pull-request.yml` is part of `.syncignore` https://github.com/paketo-buildpacks/occam/blob/650b1d8359147894114b55d32ba707acf4f702b0/.github/.syncignore#L1
Keep the pipelines alive
=> update the `actions/upload-artifact` from v2 to v3

pack.go, pack_test.go
This allows to add additional arguments to `pack build` that were not added yet in the fluent interface.
When you realise in your test that a specific `pack build` argument is not yet supported by the fluent interface, this offers some mitigation. Otherwise, you would have to delay the test or use shell out and not `occam.Pack`.
=> Allow additional build args for pack build

container.go, container_test.go
This PR adds an extra check if the value is defined when accessing the port of the container inspect. 
https://github.com/paketo-buildpacks/occam/blob/0fb03539e1d75afb0b91051ba3a92a5197c78336/container.go#L44-L46
Specifically, there is a chance the container having a port which doesnt map on any host port. In that case there is no value and as a result when accessing the `value[0].HostPort` the function crashes.
With this PR we ensure that before accessing the value, the value is defined by checking the length of the array.
Unit tests for testing the `NewContainerFromInspectOutput` function has been added.
Safely accessing a potential undefined variable.
=> Avoid accessing undefined hostports which causes an error

.github/workflows/create-draft-release.yml, .github/workflows/lint.yml, .github/workflows/test-pull-request.yml, go.mod, go.sum
Upgrading to Go 1.21 has caused a number of failures in our various buildpacks. We should upgrade the Go versio eventually, but we should do it as a more organized effort
=> use go 1.20

packagers/jam.go, packagers/jam_test.go, packagers/libpak.go, packagers/libpak_test.go
This fixes issues when testing on macos
=> Buildpack packaging should always target linux

go.mod, go.sum
This change bumps the docker library to 26.1.5 to resolve [cve-2024-41110](https://avd.aquasec.com/nvd/2024/cve-2024-41110/).
We noticed `HIGH` vulnerabilities when scanning containers built with the node-js buildpack caused by the `0-setup-symlinks` binary from the npm-install buildpack.
cccam is used here
https://github.com/paketo-buildpacks/npm-install/blob/a01f9fc34b8cb106f8c7503f13ab70952533f157/go.mod#L9
Sample output from trivy scan
```
layers/paketo-buildpacks_npm-install/launch-modules/exec.d/0-setup-symlinks (gobinary)
Total: 1 (HIGH: 0, CRITICAL: 1)
┌──────────────────────────┬────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬────────────────────────────────────────────┐
│         Library          │ Vulnerability  │ Severity │  Installed …
```
=> Bump docker to version 26.1.5 to fix CVE-2024-41110

packagers/jam.go, packagers/jam_test.go
Recent change to support multi-arch for buildpacks brokle occam for extensions. This was because extensions were being built with "pack buildpack package" which seems to work for extensions if a tgz is passed in but not an expanded directory.
Update to use "pack extension package" for extensions instead. Unfortunately pack does not yet seem to support multi-arch for extensions so we'll have to add the --target option for extensions after that has been added.
=> fix: restore ability to use occam with extensions

matchers/have_file.go, matchers/have_file_test.go, matchers/have_file_with_content.go, matchers/have_file_with_content_test.go
This change introduces a new feature that allows users to include checking symlinks to files in their file matcher tests.
When a user checks a file in an OCI image, using `have_file()` or `have_file_with_content()` would return `false` if the provided path was a symlink, regardless of the actual existence of the target file. With this feature, the functions now correctly follow symlinks to verify the existence and content of the target file.
=> feat: filematchers follow symlinks

packagers/jam.go, packagers/jam_test.go
This PR adds the capability in occam to package a multi-arch extension based on the architecture of the OS, similar to what we do on buildpack but for extension.
=> Adding support for packaging multi-arch extension based on the OS architecture
